### ISSUE TITLE
Telemetry data

### ISSUE THREAD

**Issue by Guangwen11** [dallongo/rFactorSharedMemoryMap#1]
Hello, I downloaded the rFactor1 plug-in, but the website provided does not seem to be able to download it; if possible, I would like to know whether there is a shared memory method for Automobilista1's telemetry data acquisition!

**Comment by dallongo** [comment]
Hi, the compiled binary is available from the releases page on this repository: https://github.com/dallongo/rFactorSharedMemoryMap/releases/download/2.0.0.0/rFactorSharedMemoryMap.dll

**Comment by Guangwen11** [comment]
Okay, I got it.
